#!/bin/bash
. ./config.cfg

yum -y install gawk bc wget lsof

# Check VPS information
./components/info
sleep 3

printf "=========================================================================\n"
printf "Preparing to install... \n"
printf "=========================================================================\n"
./components/setup_domain_port

./components/setup_basic_linux_env

# Install EPEL + Remi Repo
yum -y install epel-release yum-utils
rpm -Uvh $remi_rpm_version

# Install Nginx Repo
rpm -Uvh $nginx_centos_rpm_version

# Install MariaDB Repo 10.0
cp ./lib/MariaDB.repo /etc/yum.repos.d/MariaDB.repo

systemctl stop  saslauthd.service
systemctl disable saslauthd.service

# Disable the FirewallD Service and use Iptables instead because FirewallD need reboot in order to start
systemctl stop firewalld
systemctl disable firewalld
systemctl mask firewalld

yum -y remove mysql* php* httpd* sendmail* postfix* rsyslog*
yum clean all
yum -y update

sleep 3
./components/install_server

sleep 3
./components/configure_server

sleep 3
./components/setup_mariadb

sleep 3
./components/install_wordpress

sleep 3
./components/setup_admin_script

# Server Info
sleep 3
./components/setup_server_info

# phpMyAdmin
sleep 3
./components/setup_phpadmin

# Log Rotation
sleep 3
./components/configure_log

# Change port SSH
sleep 3
./components/change_ssh_port

sleep 3
./components/grant_permission

sleep 3
./components/install_helper_script

sleep 3
printf "=========================================================================\n"
printf "Script Admin: http://$server_name:$admin_port/ \n or http://$server_ip:$admin_port/\n\n"
printf "phpMyAdmin: http://$server_name:$admin_port/phpmyadmin/ \n or http://$server_ip:$admin_port/phpmyadmin/\n\n"
printf "Server Info: http://$server_name:$admin_port/serverinfo/ \n or http://$server_ip:$admin_port/serverinfo/\n\n"
printf "PHP OPcache: http://$server_name:$admin_port/op.php \n or http://$server_ip:$admin_port/op.php\n"
printf "=========================================================================\n"
printf "Login info:\n"
printf " Username: admin\n"
printf " Password: $admin_password\n"
printf "=========================================================================\n"
printf "Server will auto reboot in 3s.... \n\n"
sleep 3
reboot
exit
