#!/bin/bash

# wget -q $script_url/hocvps -O /bin/hocvps && chmod +x /bin/hocvps
# mkdir /etc/hocvps/menu/
# cd /etc/hocvps/menu/
# wget -q $script_url/component/menu.zip
# unzip -q menu.zip && rm -f menu.zip
# chmod +x /etc/hocvps/menu/*

# cat > "/root/hocvps-script.txt" <<END
# =========================================================================
#                            MANAGE VPS INFORMATION
# =========================================================================
# Lenh truy cap menu HocVPS Script: hocvps

# Domain chinh: http://$server_name/ hoac http://$server_ip/

# HocVPS Script Admin:    http://$server_name:$admin_port/ hoac http://$server_ip:$admin_port/
# File Manager:       http://$server_name:$admin_port/filemanager/ hoac http://$server_ip:$admin_port/filemanager/
# phpMyAdmin:     http://$server_name:$admin_port/phpmyadmin/ hoac http://$server_ip:$admin_port/phpmyadmin/
# Server Info:        http://$server_name:$admin_port/serverinfo/ hoac http://$server_ip:$admin_port/serverinfo/
# PHP OPcache:        http://$server_name:$admin_port/op.php hoac http://$server_ip:$admin_port/op.php

# Thong tin dang nhap mac dinh cho tat ca tool:
# Username: admin
# Password: $admin_password

# Neu can ho tro, cac ban hay truy cap https://hocvps.com/script/
# END

# chmod 600 /root/hocvps-script.txt